# Generated by Django 2.2.5 on 2019-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191215_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
